### ISSUE TITLE
Changing camera orientation in AddRecipe / EditRecipe crashes app

### ISSUE THREAD

**Issue by martha-gao** [MarMigMon/FoodApp#125]

**Comment by monicatang** [comment]
![screen shot 2018-08-06 at 2 19 21 pm](https://user-images.githubusercontent.com/30488454/43741624-dc5e4fbe-9983-11e8-89f2-a742549a1744.png)

**Comment by monicatang** [comment]
In the add recipe fragment, a null pointer exception is thrown because recipeImage is null when the saved instance state is restored. recipeImage is not set by the time onViewCreated is called (before onActivityResult), might need to save file path instead and pass that to intent (?)
